### ISSUE TITLE
errors if J interface is not found

### ISSUE THREAD

**Issue by carandraug** [JamieHeather/stitchr#1]
`determine_j_interface` is supposed to return a two element tuple.  However, if the J interface is not found, stitchr is quite cryptic. Example:

```
$ python stitchr.py -v TRAV1-2 -j TRAJ33 -cdr3 CAVERGEGF
Traceback (most recent call last):
  File "stitchr.py", line 107, in <module>
    c_term_nt_trimmed, cdr3_c_end = fxn.determine_j_interface(input_args['cdr3'], c_term_nt, c_term_aa)
TypeError: 'NoneType' object is not iterable
```

This is because the condition inside the for loop in `determine_j_interface` is never met, so the for loop ends and defaults to return `None`. 

I would guess that either `determine_j_interface` should raise an error, or stitchr should check the return value and exit with a nicer message.

**Comment by JamieHeather** [comment]
Ahh this is a good catch, thanks! 

This is related to issue #2 - it's never finding the Js in these examples because the Js aren't there to be found. I've changed the way it looks for Js now too - previously it *had* to match at least a 4-mer, but it's more flexible now (although this required a few more sanity checks added). However given the length of the J downstream of what is typically deleted this shouldn't come up much, as we should have a nice section to find - provided we're working with plausible J/CDR3 combinations anyway!
