### ISSUE TITLE
Simplifying output / silent mode

### ISSUE THREAD

**Issue by EdGreen21** [JamieHeather/stitchr#22]
Great tool - one feature request would be to have an output switch for a simplified output reporting of just the NT or AA sequence. 

This would make it easier to implement stitchr with other pipelines (in our case in R through reticulate), without having to process the intermediate output files (i.e. strip out the fasta header and select just AA or NT).  **--aa/--nt** ?

**Comment by JamieHeather** [comment]
Thanks Ed, a great suggestion. I actually had already dabbled with something in a similar vein so this was an easy one to introduce, very happy to get it working with more use cases.

I can't use --aa/--nt due to clashes with existing/potential future flags, but I've added a -m / --mode field, which can be used to specify either pure aa/nt sequences, or the default/single FASTAs. See v0.10.1 / 60faffb.
