### ISSUE TITLE
TRDV2 error

### ISSUE THREAD

**Issue by zacharyzale** [JamieHeather/stitchr#25]
I get the following error when running stitchr or thimble on TRDV2:

`can only concatenate list (not "str") to list`

It appears to be a python error. I have no issues with any of the other Delta chains. Do you know how to resolve?

**Comment by JamieHeather** [comment]
(Oops, didn't mean to close that).

OK so this is easily solved without any fixes: it's trying to use a leader sequence that's not present in the reference. Assuming we're talking human, the only TRDV2 leader is for *03, which you can specify via the `-l` flag. So for example the following works:

```
python3 stitchr.py -v TRDV2*01 -j TRDJ1*01 -cdr3 CACDTIRPKFSTDKLIF -l TRDV2*03
```

However that's definitely not the expected error state! Thanks for pointing this out.

**Comment by JamieHeather** [comment]
Note for posterity.

The code used to assume that every gene region (leader/V/J/C) had at the very least a prototypical allele (*01), so when a gene was requested without an allele this was the safe default option. The problem here arose for a gene where this was not true, as there was a V gene that GENE-DB had a valid prototypical  (TRDV2*01) but which lacked a corresponding prototypical leader allele (the only one available for the gene being TRDV2*03). As such the defaulted sequence was not available, and it failed without a useful error message.

Now the code has edited to follow this process when an allele is not provided:

1) Look for a prototypical allele
2) If it doesn't exist, pick an allele from those that do exist (flagging up a warning that it's done this)
3) If it does, use the the prototypical allele (but check if other alleles exist, and if it does flag that up too)

(Note this only applies for genes that do exist in the data; asking for a non-featured gene will still throw a ValueError).

As always, in general the best results are achieved by specifying exactly which alleles you want where possible, and keeping track of which alleles are used in your stitched sequences.
