### ISSUE TITLE
TRBD gene

### ISSUE THREAD

**Issue by marshelma** [JamieHeather/stitchr#41]
Hi, thank you for this very useful tool! 

I'm new to TCR assemble so it might be a naive question. May I know why there is no option to fill in the TRBD gene ? There are three different TRBD allele in my dataset:
TRBD1*01 TRBD2*01 TRBD2*02 
Are they all the same? Will not including them make the output inaccurate?

**Comment by JamieHeather** [comment]
Hello,

You're welcome (and thanks)!

There's no option for D genes because it doesn't really make a difference to stitchr. In a rearranged receptor all of the D gene residues are wholly contained inside the CDR3, so when you give stitchr the CDR3 it already has all the D sequence included.

(Just for the record the TRBD alleles do differ slightly. However they're very short and often pretty nibbled during VDJ recombination so it's often impossible to tell which was used - hence why D gene assignment isn't as much of a thing in TCR research like it is for BCRs.)

Cheers,
Jamie

**Comment by marshelma** [comment]
Thank you so much for the fast reply! It is very clear!
