### ISSUE TITLE
Integration with tidytcells

### ISSUE THREAD

**Issue by yutanagano** [JamieHeather/stitchr#42]
Hello! I'm Yuta, current PhD candidate at the Chain lab. A big fan of and user of stitchr- thank you for the software!

I understand that stitchr by construction expects IMGT-compliant V/J gene symbols as input, and I'm finding myself often using stitchr in conjunction with a software I wrote myself called [tidytcells](https://github.com/yutanagano/tidytcells) that can dynamically auto-correct non-standard TR gene symbols.

Was wondering if you think tidytcells would be a useful tool to be either integrated into stitchr's input parsing? Or if not then referenced in the docs when mentioning IMGT standardization of input?

Kind of a plug for tidytcells 😁 but also thought it might actually help some people out!

**Comment by JamieHeather** [comment]
Hi Yuta,

Thanks, very nice of you to say!

I had indeed seen tidytcells, which looks great. I'm open to seeing how this could integrate - maybe I'll reach out to discuss how best this could work.  Either way I'm very happy pointing that out in the stitchr docs, as I've definitely had people hit stitchr errors due to formatting errors in their input allele names!

**Comment by JamieHeather** [comment]
I'm actually working on some minor tweaks at the moment, including the docs, so I can add in the suggestion no problem.

The only thing that makes me a little nervous about instituting an automatic check is that it might not cope so well with odd/uncommon/non-natural sequences (which are things that I often put through myself, and which did upset things in earlier test versions). For example I've recently been playing with some funny ORF alleles, like the human TRBV7-3*03, which uses Arg instead of the usual conserved second Cys, which I think `tidytcells` might break the sequences of. Hence generally I've mostly made `stitchr` to work under the assumption that users are best placed to get their own data sorted upstream, and just instead raise warnings if it thinks something might have gone awry.

However I can certainly imagine that many users won't care about those edge cases, especially when trying to adapt large datasets. I think maybe it could be included as an optional check, triggered via a flag when running. Perhaps even separate flags for `tidytcells.tr.standardize` and `tidytcells.junction.standardize`, to allow users a bit more flexibility.

**Comment by yutanagano** [comment]
Thanks for adding a note in the docs! I don't know if my email reply to you came through but I see what you mean about edge cases and that perhaps best practice is to have standardisation and stitching be two separate steps. Anyways I hope our tools combined can have a synergistic effect and help some TCR people out there :).
