### ISSUE TITLE
A issue about stitching immunoglobulins

### ISSUE THREAD

**Issue by DawnChou** [JamieHeather/stitchr#43]
Hi, I am trying to apply stitchr to BCR, but I met some problems.

Following the [instruction](https://jamieheather.github.io/stitchr/immunoglobulins.html#), I tried using [this modified version of stitchrdl](https://gist.github.com/JamieHeather/bb86ea2c5968bf93a6c1df59c8849435) to download formatted human immunoglobulin sequences from IMGT. However, it didn't create _IGH.fasta  IGK.fasta  IGL.fasta_ under 'HUMAN-IG' data folder due to the warnings:

<img width="1403" alt="1716358867528" src="https://github.com/JamieHeather/stitchr/assets/47439428/914644b7-3880-4d75-8fb3-a5f18c634b04">

I don't know why it occurred, and I revised the code of [this modified version of stitchrdl](https://gist.github.com/JamieHeather/bb86ea2c5968bf93a6c1df59c8849435) in line 304 from `if len(region_counts[loc]) >= 4:` to `if len(region_counts[loc]) >= 2:` (I am not sure whether this is correct but I just want the code to create _IGH.fasta  IGK.fasta  IGL.fasta_ under 'HUMAN-IG' data folder. 
Well, the modify did create the _IGH.fasta  IGK.fasta  IGL.fasta_ under 'HUMAN-IG' data folder. However, when I run the example `stitchr -v IGHV3-30-3*01 -j IGHJ4*02 -cdr3 CARLSPAGGFFDYW -c IGHM*01 -s HUMAN-IG -n JQ304252`, it raises errors: `Exception: No entries for CONSTANT in IMGT data.`
Now there is no way for me to run stitchr on BCR successfully. Is there any method to fix this? Thanks.

**Comment by JamieHeather** [comment]
Hello hello,

So unfortunately this is one of those consequences of my being a TCR person who doesn't really do much BCR stuff, so little problems don't get caught early!

In this case this was due to the fact that IG constant region sequences are scraped in a separate command, and the URL I copied for the API from their website only had 'http' not 'http*s*'. I guess since I first wrote and tested that script IMGT tweaked their settings so that http scrapes were rejected, so this script wasn't catching any constant regions and so none of the loci were stitchable.

I've [fixed the gist now (v0.2.0)](https://gist.github.com/JamieHeather/bb86ea2c5968bf93a6c1df59c8849435), and confirmed that works at least on my setup. Please reopen and let me know if that doesn't get it working for you.

Also all those "Skipping gene sequence" warnings are unrelated - that's just stitchr avoiding alleles with ambiguous bases - which IG has far more. As mentioned in the user guide, everything is trickier in BCRs than TCRs, so the best thing to do is generate donor-specific germline references (potentially also with hypermutated entries) as a starting point.

Cheers,
Jamie
